*&---------------------------------------------------------------------*
*&  Include           ZP0008_P040_TOP
*&---------------------------------------------------------------------*

DATA: GT_VISIT     TYPE TABLE OF ZP0008_T0020,
      GT_VISIT2    TYPE TABLE OF ZP0008_T0020,
      GS_VISIT     TYPE ZP0008_T0020,
      GS_VISIT2     TYPE ZP0008_T0020,

      GT_EMP       TYPE TABLE OF ZP0008_T0018,
      GS_EMP       TYPE ZP0008_T0018,
      GS_EMPSINGLE TYPE  ZP0008_T0018,

      GT_CUS       TYPE TABLE OF ZP0008_T0019,
      GS_CUS       TYPE ZP0008_T0019.

DATA:GV_RAPORIDNUM TYPE INT2.

DATA: IT_SELECTED_ROWS TYPE LVC_T_ROW. "ALV'den seçilen satırları almak için.
DATA: LS_SELECTED_ROW LIKE LINE OF IT_SELECTED_ROWS.

DATA: GO_ALV    TYPE REF TO CL_GUI_ALV_GRID,
      GO_CONT   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GT_FCAT   TYPE LVC_T_FCAT,
      GS_FCAT   TYPE LVC_S_FCAT,
      GS_LAYOUT TYPE LVC_S_LAYO.
DATA GV_BOL TYPE C.
DATA:
  GV_EMNICKNAME TYPE ZP0008_T0018-EMNICKNAME,
  GV_EMSIFRE    TYPE ZP0008_T0018-EMSIFRE,

  GV_EMID       TYPE ZP0008_T0020-EMID,
  GV_CUSID      TYPE ZP0008_T0020-CUSID,
  GV_RAPORID    TYPE ZP0008_T0020-RAPORID,
  GV_TARIH      TYPE ZP0008_T0020-TARIH,
  GV_ZIYARETTUR TYPE ZP0008_T0020-ZIYARETTUR,
  GV_YAPILANIS  TYPE ZP0008_T0020-YAPILANIS.

DATA: LV_MAX_RAPORID TYPE ZP0008_T0020-RAPORID.
" En yüksek RAPORID değerini bulmak için tabloyu dolaş


DATA: ITEXT TYPE TABLE OF TLINE-TDLINE,
      XTEXT TYPE TLINE-TDLINE.

DATA:
  DOCKINGLEFT TYPE REF TO CL_GUI_DOCKING_CONTAINER,
  TEXT_EDITOR TYPE REF TO CL_GUI_TEXTEDIT,
  REPID       TYPE SYREPID.

DATA: LV_MESSAGE TYPE STRING,
      LV_TYPE    TYPE STRING.

DATA: GO_SPLI TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GO_SUB1 TYPE REF TO CL_GUI_CONTAINER,
      GO_SUB2 TYPE REF TO CL_GUI_CONTAINER.

DATA: GO_DOCU TYPE REF TO CL_DD_DOCUMENT.

CLASS CL_EVENT_RECEIVER DEFINITION DEFERRED. "Böyle bir sınıfım var
"Bu yüzden altaki alan sınfımı göremediği vakit kızmayacak
"Bu genelde kod satırların sıralamasında olabilecek kısa hatalardır
DATA: GO_EVENT_RECEIVER TYPE REF TO CL_EVENT_RECEIVER.


DATA:
  LR_EXCEL_STRUCTURE      TYPE REF TO DATA,
  LO_SOURCE_TABLE_DESCR   TYPE REF TO CL_ABAP_TABLEDESCR,
  LO_TABLE_ROW_DESCRIPTOR TYPE REF TO CL_ABAP_STRUCTDESCR,
  LV_CONTENT              TYPE XSTRING,
  LT_BINARY_TAB           TYPE TABLE OF SDOKCNTASC,
  LV_LENGHT               TYPE I,
  LV_FIELNAME             TYPE STRING,
  LV_PATH                 TYPE STRING,
  LV_FULLPATH            TYPE STRING.